# Generated by Django 4.2.6 on 2023-10-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('isu_id', models.IntegerField(null=True)),
            ],
        ),
    ]
