# Generated by Django 4.2.6 on 2023-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('handler', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='workflow_state',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
