# Generated by Django 4.2.6 on 2023-11-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_workflowitem_user_workflow_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('name', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkflowItem',
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='context',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.user'),
        ),
    ]
